### ISSUE TITLE
show title is broken

### ISSUE THREAD

**Issue by igenaya** [rsimmons/subadub#33] opened 2021-10-19 09:37 UTC
The show title is broken, how to fix this????

![Screenshot (437)](https://user-images.githubusercontent.com/83929909/137884136-b9799a86-4d73-42a8-a05d-fd159683822b.png)

**Comment by cyphar** [comment] 2022-03-11 11:28
This is a duplicate of #32.

**Closed** 2024-04-13 02:55 UTC
