### ISSUE TITLE
Not working with new netflix?

### ISSUE THREAD

**Issue by venturiq** [rsimmons/subadub#31] opened 2021-09-08 15:46 UTC
It worked perfectly yesterday. Today I've noticed that netflix changed their design of the website. Does this have anything to do with my subadub not working?

edit: re-installing the addon didn't change anything.

**Comment by rsimmons** [comment] 2021-09-08 17:19
Hi, thanks for reporting this. It appears to be a duplicate of #29, I guess the new UI has rolled out to everyone. I'll close this and track it on #29.

**Closed by rsimmons** 2021-09-08 17:19 UTC
Labels: duplicate
